# Generated by Django 5.0.14 on 2026-08-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
