# Generated by Django 5.0.14 on 2026-08-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_chat_last_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='client_status',
            field=models.CharField(choices=[('first_time', 'First time'), ('follow_up', 'Follow up'), ('existing_client', 'Existing client')], default='first_time', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
